hf_model_path="/data_fast/jiaruiyu/workstation/user_data_analysis/LLM_post_training/output/250530_250630_completion_v1_sp_training_0731_deduplication_0.75_5_50k"

model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.16_250811/global_step_78/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.16_250811/global_step_65/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.18_2_250811/global_step_70/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.18_2_250811/global_step_84/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"

# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.16_250811/global_step_91/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.17_250811/global_step_24/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.17_250811/global_step_48/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.17_250811/global_step_72/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"

# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.17_250811/global_step_96/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.17_250811/global_step_168/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.18_2_250811/global_step_98/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"

# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.14_250811/global_step_44/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.14_250811/global_step_13/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.14_250811/global_step_26/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.14_250811/global_step_39/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.14_250811/global_step_52/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.14_250811/global_step_65/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.14_250811/global_step_78/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.14_250811/global_step_91/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.14_250811/global_step_104/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.14_250811/global_step_117/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.14_250811/global_step_130/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.14_250811/global_step_143/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.14_250811/global_step_156/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.14_250811/global_step_169/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"

# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.10_250811/global_step_90/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.10_250811/global_step_100/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.10_250811/global_step_110/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"

