hf_model_path="/data_fast/jiaruiyu/workstation/user_data_analysis/LLM_post_training/output/250530_250630_completion_v1_sp_training_0731_deduplication_0.75_5_50k"

# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_44/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_11/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_22/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_33/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_44/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_55/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_66/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_77/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_88/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_99/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_110/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_121/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_143/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_154/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_165/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_176/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_187/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.13_250811/global_step_198/actor"
/data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"

# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.10_250811/global_step_90/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.10_250811/global_step_100/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"
# model_path="/data_large/liangxiaoyun/model_output/grpo-v8.6.10_250811/global_step_110/actor"
# /data_train/liangxiaoyun/miniconda3/envs/verl/bin/python3 model_merger.py merge --backend "fsdp" --local_dir $model_path --hf_model_path $hf_model_path --target_dir $model_path"_merge"

