name: ray

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths:
      - "**/*.py"
      - .github/workflows/ray_test.yml
  pull_request:
    branches:
      - main
    paths:
      - "**/*.py"
      - .github/workflows/ray_test.yml

jobs:
  ray:
    runs-on: self-host-gpu
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install yapf
      #     pip install toml==0.10.2
      - name: Running some ray test that only need 2 GPUs
        run: |
          pytest -s -x test_rvdz.py test_driverfunc_to_worker.py test_data_transfer.py test_colocated_workers.py test_check_worker_alive.py
